/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author asterix
 */
public class HV_DesktopMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form HV_DesktopMainFrame
     */
    public HV_DesktopMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_desktopMain = new javax.swing.JPanel();
        btn_administration = new javax.swing.JButton();
        jPanel_desktopFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar_desktop = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        jMenu_file_closeDesktop = new javax.swing.JMenu();
        jMenu_edit = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel_desktopMainLayout = new javax.swing.GroupLayout(jPanel_desktopMain);
        jPanel_desktopMain.setLayout(jPanel_desktopMainLayout);
        jPanel_desktopMainLayout.setHorizontalGroup(
            jPanel_desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_desktopMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_administration)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_desktopMainLayout.setVerticalGroup(
            jPanel_desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_desktopMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_administration)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_desktopFooterLayout = new javax.swing.GroupLayout(jPanel_desktopFooter);
        jPanel_desktopFooter.setLayout(jPanel_desktopFooterLayout);
        jPanel_desktopFooterLayout.setHorizontalGroup(
            jPanel_desktopFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel_desktopFooterLayout.setVerticalGroup(
            jPanel_desktopFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desktopFooterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu_file.setText("Datei");

        jMenu_file_closeDesktop.setText("jMenu3");
        jMenu_file.add(jMenu_file_closeDesktop);

        jMenuBar_desktop.add(jMenu_file);

        jMenu_edit.setText("Bearbeiten");

        jMenu4.setText("jMenu4");
        jMenu_edit.add(jMenu4);

        jMenuBar_desktop.add(jMenu_edit);

        setJMenuBar(jMenuBar_desktop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_desktopMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_desktopFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_desktopMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_desktopFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HV_DesktopMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HV_DesktopMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HV_DesktopMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HV_DesktopMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HV_DesktopMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar_desktop;
    private javax.swing.JMenu jMenu_edit;
    private javax.swing.JMenu jMenu_file;
    private javax.swing.JMenu jMenu_file_closeDesktop;
    private javax.swing.JPanel jPanel_desktopFooter;
    private javax.swing.JPanel jPanel_desktopMain;
    // End of variables declaration//GEN-END:variables
}
